POST http://localhost:3001/api/rooms/create HTTP/1.1
content-type: application/json

{
    "user": {
        "id": "CREATOR_ID",
        "name": "Steve"
    }
}
###

POST http://localhost:3001/api/rooms/join/CDSL HTTP/1.1
Content-Type: application/json

{
  "user": {
    "id": "1234UNIQUEID",
    "name": "Gigi"
  }
}